### ISSUE TITLE
Does not seem to work with yaml

### ISSUE THREAD

**Issue by nkakouros** [pseewald/AnyFold#29]
Thanks for this plugin.

This is how I have anyfold configured:

```
  " Minimalistic display of closed folds
  let g:anyfold_fold_display = 1

  " Fold multiline comments
  let g:anyfold_fold_comments = 1
  let g:anyfold_identify_comments = 2
  let g:anyfold_comments = []
```

I am trying to have folds in yaml files based on indent. The following file:

```yaml
- dfdfdf: 223
  dfdf: 23423
  sdfsdf:
    sdfsdf: 1232
    sdfsdf: 1232
    sdfsdf: 1232
  sdfsdf:
    sdfsdf: 1232
    sdfsdf: 1232
    sdfsdf: 1232
```

however produces a single fold with anyfold that folds the whole file. I would expect it to produce two more folds on the inner indents. Am I doing sth wrong? Is this by design? Can I somehow enable the inner folds as well?
